spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

file:
  download:
#    location: /Users/leejinseok/Study/spring-session/download
    location: C:\Users\sonak\Study\spring-session-study\download
  upload:
#    location: /Users/leejinseok/Study/spring-session/upload
    location: C:\Users\sonak\Study\spring-session-study\upload
